# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S73j7nPgu9RM1RJVTCsvBvwKP6Ve5XB8
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

sns.set_theme(style="whitegrid")

df=pd.read_csv('Weather Data.csv',parse_dates=['Date/Time'])
df.set_index('Date/Time', inplace=True)
print("--- Dataset Summary ---")
print (df.info())

df = df.dropna()

print("\n--- Summary Statistics ")
print(df.describe())

plt.figure(figsize=(8,5))
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Weather Metrics')
plt.show()


plt.figure(figsize=(12,5))
plt.plot(df.index, df ['Temp_C'], label='Temperature', color='orange')
# Since TempMax and TempMin columns are not present, plotting Temp_C as a general temperature trend.
plt.title('Temperature Trends Over Time')
plt.xlabel('Date/Time')
plt.ylabel('Temperature (°C)')
plt.legend()
plt.show()

df['Tomorrow_TempMax'] = df['Temp_C'].shift(-1)
df = df.dropna()
X= df[[ 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%','Wind Speed_km/h']]
y= df['Tomorrow_TempMax']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
r2= r2_score(y_test, predictions)
print(f"Mean Squared Error(MSE): {mse:.2f}")
print(f"R-squared Score (R^2): {r2:.2f}")


plt.figure(figsize=(7,7))
plt.scatter(y_test, predictions, alpha=0.5, color='purple')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel('Actual Tomorrow TempMax (°C)')
plt.ylabel('Predicted Tomorrow TempMax (°C)')
plt.title('Actual vs. Predicted Temperatures')
plt.show()